# config/config_player.py
"""
Configuration for the player character, including defaults, stats, and leveling.
"""

# --- Player Defaults & Base Values ---
PLAYER_DEFAULT_NAME = "Adventurer"
PLAYER_DEFAULT_MAX_MANA = 50
PLAYER_DEFAULT_RESPAWN_REGION = "town"
PLAYER_DEFAULT_RESPAWN_ROOM = "town_square"
PLAYER_BASE_ATTACK_POWER = 5
PLAYER_BASE_DEFENSE = 3
PLAYER_BASE_ATTACK_COOLDOWN = 2.0
PLAYER_BASE_MANA_REGEN_RATE = 1.0
PLAYER_BASE_HEALTH_REGEN_RATE = 1.0
PLAYER_DEFAULT_KNOWN_SPELLS = ["magic_missile", "minor_heal"]
PLAYER_MAX_COMBAT_MESSAGES = 10
PLAYER_DEFAULT_MAX_TOTAL_SUMMONS = 100
DEFAULT_PLAYER_NAME = 'Adventurer'

# --- Player Health Calculation ---
PLAYER_BASE_HEALTH = 80
PLAYER_CON_HEALTH_MULTIPLIER = 2.0
PLAYER_LEVEL_HEALTH_BASE_INCREASE = 5
PLAYER_LEVEL_CON_HEALTH_MULTIPLIER = 0.5

# --- Player Stats & Leveling ---
PLAYER_DEFAULT_STATS = {
    "strength": 10, "dexterity": 10, "intelligence": 10,
    "wisdom": 10, "constitution": 10, "agility": 10,
    "spell_power": 5, "magic_resist": 2,
    "resistances": {} # NEW: Add default resistances dictionary
}
PLAYER_BASE_XP_TO_LEVEL = 100
PLAYER_XP_TO_LEVEL_MULTIPLIER = 1.5
PLAYER_LEVEL_UP_STAT_INCREASE = 1
PLAYER_MANA_LEVEL_UP_MULTIPLIER = 1.15
PLAYER_MANA_LEVEL_UP_INT_DIVISOR = 2
PLAYER_MANA_REGEN_WISDOM_DIVISOR = 20
PLAYER_HEALTH_REGEN_STRENGTH_DIVISOR = 25
PLAYER_ATTACK_POWER_STR_DIVISOR = 3
PLAYER_DEFENSE_DEX_DIVISOR = 4
PLAYER_REGEN_TICK_INTERVAL = 1.0

# --- Player Combat ---
PLAYER_BASE_HIT_CHANCE = 0.85
PLAYER_ATTACK_DAMAGE_VARIATION_RANGE = (-1, 2)

# --- Player Status Display ---
PLAYER_STATUS_HEALTH_CRITICAL_THRESHOLD = 25
PLAYER_STATUS_HEALTH_LOW_THRESHOLD = 50