# config/config_display.py
"""
Configuration for display settings, colors, fonts, and UI elements.
"""

# Display settings
SCREEN_WIDTH = 1600
SCREEN_HEIGHT = 920
FONT_FAMILY = "helvetica"
FONT_SIZE = 18
TITLE_FONT_SIZE_MULTIPLIER = 2
LINE_SPACING = 5
INPUT_HEIGHT = 30
TARGET_FPS = 30

# UI Layout
STATUS_PANEL_WIDTH = 400
SIDE_PANEL_WIDTH = 250
STATUS_PANEL_PADDING = 5
STATUS_AREA_HEIGHT = 30 # Pixel height for HP/MP/XP bars area
LOAD_SCREEN_MAX_SAVES = 10
LOAD_SCREEN_COLUMN_WIDTH_FACTOR = 0.6
VENDOR_LIST_ITEM_NAME_WIDTH = 25
VENDOR_LIST_PRICE_WIDTH = 4

# Colors
TEXT_COLOR = (255, 255, 255)  # White
BG_COLOR = (0, 0, 0)  # Black
INPUT_BG_COLOR = (50, 50, 50)  # Dark gray
DEBUG_COLOR = (255, 0, 0)  # Red for debug text

COLOR_PURPLE = (255, 0, 255)
COLOR_RED = (255, 0, 0)
COLOR_ORANGE = (255, 165, 0)
COLOR_YELLOW = (255, 255, 0)
COLOR_GREEN = (0, 255, 0)
COLOR_BLUE = (0, 0, 255)
COLOR_DARK_BLUE = (0, 0, 128)
COLOR_CYAN = (0, 255, 255)
COLOR_WHITE = (255, 255, 255)
COLOR_GRAY = (192, 192, 192)
COLOR_BEIGE = (245, 222, 179)
COLOR_STEEL_BLUE = (173, 216, 230)
COLOR_DEFAULT = COLOR_WHITE

# Format Codes
FORMAT_PURPLE = "[[PURPLE]]"
FORMAT_RED = "[[RED]]"
FORMAT_ORANGE = "[[ORANGE]]"
FORMAT_YELLOW = "[[YELLOW]]"
FORMAT_GREEN = "[[GREEN]]"
FORMAT_BLUE = "[[BLUE]]"
FORMAT_DARK_BLUE = "[[DARK_BLUE]]"
FORMAT_GRAY = "[[GRAY]]"
FORMAT_BEIGE = "[[BEIGE]]"
FORMAT_STEEL_BLUE = "[[STEEL_BLUE]]"
FORMAT_CYAN = "[[CYAN]]"
FORMAT_WHITE = "[[WHITE]]"
FORMAT_RESET = "[[/]]"

# Semantic Format Codes
FORMAT_ERROR = FORMAT_RED
FORMAT_TITLE = FORMAT_YELLOW
FORMAT_HIGHLIGHT = FORMAT_GREEN
FORMAT_SUCCESS = FORMAT_GREEN
FORMAT_CATEGORY = FORMAT_CYAN
FORMAT_FRIENDLY_NPC = FORMAT_BEIGE

# Default color mapping for format codes
DEFAULT_COLORS = {
    FORMAT_PURPLE: COLOR_PURPLE,
    FORMAT_RED: COLOR_RED,
    FORMAT_ORANGE: COLOR_ORANGE,
    FORMAT_YELLOW: COLOR_YELLOW,
    FORMAT_GREEN: COLOR_GREEN,
    FORMAT_BLUE: COLOR_BLUE,
    FORMAT_DARK_BLUE: COLOR_DARK_BLUE,
    FORMAT_STEEL_BLUE: COLOR_STEEL_BLUE,
    FORMAT_GRAY: COLOR_GRAY,
    FORMAT_CYAN: COLOR_CYAN,
    FORMAT_WHITE: COLOR_WHITE,
    FORMAT_RESET: COLOR_DEFAULT,
    FORMAT_FRIENDLY_NPC: COLOR_BEIGE
}

# Semantic mapping for easier use
SEMANTIC_FORMAT = {
    "TITLE": FORMAT_ORANGE,
    "CATEGORY": FORMAT_BLUE,
    "HIGHLIGHT": FORMAT_CYAN,
    "SUCCESS": FORMAT_GREEN,
    "ERROR": FORMAT_RED,
    "NEUTRAL": FORMAT_YELLOW,
    "DEFAULT": FORMAT_RESET
}

# UI Messages
GAME_OVER_MESSAGE_LINE1 = "YOU HAVE DIED"
GAME_OVER_MESSAGE_LINE2 = "Press 'R' to Respawn or 'Q' to Quit to Title"
HELP_MAX_COMMANDS_PER_CATEGORY = 5